# Generated by Django 3.1.2 on 2020-11-15 16:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('main_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('icon1', models.ImageField(default='', upload_to='uploads/profile/project_photos')),
                ('icon2', models.ImageField(default='', upload_to='uploads/profile/project_photos')),
                ('icon3', models.ImageField(default='', upload_to='uploads/profile/project_photos')),
                ('about_me', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('about_me_photo', models.ImageField(default='', upload_to='uploads/profile/project_photos')),
                ('course_paid_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('course_paid_photo', models.ImageField(default='', upload_to='uploads/profile/project_photos')),
                ('donate_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('donate_photo', models.ImageField(default='', upload_to='uploads/profile/project_photos')),
            ],
        ),
    ]
