# Generated by Django 3.1.2 on 2022-03-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='about_me_photo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='course_paid_photo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='course_paid_text',
        ),
        migrations.RemoveField(
            model_name='home',
            name='donate_photo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='donate_text',
        ),
        migrations.RemoveField(
            model_name='home',
            name='icon2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='icon3',
        ),
    ]
