# Generated by Django 3.1.2 on 2022-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220326_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='facebook',
            field=models.CharField(default='https://www.facebook.com/', max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='instagram',
            field=models.CharField(default='https://www.instagram.com/?hl=en', max_length=500),
        ),
        migrations.AlterField(
            model_name='home',
            name='youtube',
            field=models.CharField(default='https://www.youtube.com/channel/UC8qa9USnmzi-ewkXTMiZ9LA', max_length=500),
        ),
    ]
