# Generated by Django 3.1.2 on 2022-03-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220326_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default='Home', max_length=100),
        ),
    ]
