# Generated by Django 3.1.2 on 2022-04-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_home_home_page_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='resume',
            field=models.ImageField(default='', upload_to='uploads/home/resume'),
        ),
    ]
