# Generated by Django 3.1.2 on 2022-04-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_home_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='resume',
            field=models.FileField(default='', upload_to='uploads/home/resume'),
        ),
    ]
