# Generated by Django 3.1.2 on 2022-04-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20220410_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='file_name',
            field=models.CharField(default='Resume.pdf', max_length=100),
        ),
    ]
