# Generated by Django 3.1.2 on 2022-03-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_aboutyoutube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='aboutYoutube',
            new_name='about_youtube',
        ),
    ]
