# Generated by Django 3.1.2 on 2022-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220329_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='home_page_category',
            field=models.IntegerField(default=1),
        ),
    ]
