# Generated by Django 3.1.2 on 2022-04-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220330_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='home_page_category',
            field=models.IntegerField(default=1),
        ),
    ]
