# Generated by Django 3.1.2 on 2022-04-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_home_page_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='home_page_category',
        ),
    ]
